server:
  port: 8080

spring:
  application:
    name: service-backend

  datasource:
    url: jdbc:postgresql://postgres-operational:5432/finance_operational
    username: admin
    password: 1234
    #multi-datasource

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: local-dev-secret-key-must-be-at-least-256-bits-long-for-hs256
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

firebase:
  credential-path: woorifis-service-firebase-adminsdk-fbsvc-bf3b482f03.json

mydata:
  server:
    url: http://mydata-server:8084/mydata/v1