server:
  port: 8080

spring:
  application:
    name: service-backend

  datasource:
    url: jdbc:postgresql://postgres-operational:5432/finance_operational
    username: admin
    password: 1234

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

  jpa:
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

log:
  datasource:
    url: jdbc:postgresql://postgres-log:5432/finance_log
    username: admin
    password: 1234

analytics:
  datasource:
    url: jdbc:postgresql://postgres-analytics:5432/finance_analytics
    username: admin
    password: 1234

jwt:
  secret: local-dev-secret-key-must-be-at-least-256-bits-long-for-hs256
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

firebase:
  credential-path: classpath:woorifis-service-firebase-adminsdk-fbsvc-bf3b482f03.json


mydata:
  server:
    url: http://mydata-server:8084/mydata/v1

ai:
  server:
    url: http://service-ai-server:8000/api/v1/ai

bank:
  server:
    url: http://bank-server:8081