-- =====================================================
-- service-backend Analytics DB Schema
-- PostgreSQL 16 호환
-- 주의: IF NOT EXISTS 필수 (매 기동 시 실행됨)
-- =====================================================

CREATE TABLE IF NOT EXISTS analysis_raw_transaction
(
    raw_transaction_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT         NOT NULL,
    source_type           VARCHAR(30)    NOT NULL,
    source_transaction_id BIGINT         NOT NULL,
    account_id            BIGINT,
    transaction_type      VARCHAR(50)    NOT NULL,
    category              VARCHAR(100),
    amount                DECIMAL(18, 2) NOT NULL,
    balance_after         DECIMAL(18, 2),
    transaction_at        TIMESTAMP      NOT NULL,
    raw_payload           JSONB          NOT NULL,
    synced_at             TIMESTAMP      NOT NULL,

    CONSTRAINT uk_analysis_raw_tx_source UNIQUE (source_type, source_transaction_id)
);

CREATE INDEX IF NOT EXISTS idx_analysis_raw_tx_user_id
    ON analysis_raw_transaction (user_id);
CREATE INDEX IF NOT EXISTS idx_analysis_raw_tx_transaction_at
    ON analysis_raw_transaction (transaction_at);
CREATE INDEX IF NOT EXISTS idx_analysis_raw_tx_synced_at
    ON analysis_raw_transaction (synced_at);

CREATE TABLE IF NOT EXISTS analysis_asset_snapshot
(
    snapshot_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT         NOT NULL,
    total_asset           DECIMAL(18, 2) NOT NULL,
    total_bank_asset      DECIMAL(18, 2),
    total_stock_asset     DECIMAL(18, 2),
    emergency_fund_amount DECIMAL(18, 2),
    emergency_fund_ratio  DECIMAL(5, 2),
    snapshot_at           TIMESTAMP      NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_analysis_asset_snapshot_user_id
    ON analysis_asset_snapshot (user_id);
CREATE INDEX IF NOT EXISTS idx_analysis_asset_snapshot_snapshot_at
    ON analysis_asset_snapshot (snapshot_at);
