-- =====================================================
-- service-backend Log DB Schema
-- PostgreSQL 16 호환
-- 주의: IF NOT EXISTS 필수 (매 기동 시 실행됨)
-- =====================================================

CREATE TABLE IF NOT EXISTS login_history
(
    login_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    login_type       VARCHAR(20)  NOT NULL,
    ip_address       VARCHAR(50)  NOT NULL,
    device_info      VARCHAR(255),
    fail_reason      VARCHAR(255),
    logged_at        TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS api_call_log
(
    api_log_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id      VARCHAR(255),
    service_name  VARCHAR(100) NOT NULL,
    api_name      VARCHAR(255) NOT NULL,
    http_method   VARCHAR(20)  NOT NULL,
    response_code VARCHAR(20)  NOT NULL,
    duration_ms   BIGINT,
    requested_at  TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_usage_log
(
    ai_usage_log_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT,
    session_id       BIGINT,
    model_name       VARCHAR(100) NOT NULL,
    response_time_ms BIGINT,
    request_type     VARCHAR(50),
    success_yn       BOOLEAN      NOT NULL,
    created_at       TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS system_error_log
(
    error_log_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id      VARCHAR(255),
    service_name  VARCHAR(100) NOT NULL,
    error_level   VARCHAR(20)  NOT NULL,
    error_code    VARCHAR(100),
    error_message TEXT         NOT NULL,
    request_uri   VARCHAR(500),
    resolved_yn   BOOLEAN      NOT NULL,
    resolved_memo VARCHAR(500),
    resolved_at   TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL
);
